### PR TITLE
1st develop Commit 1226 -- feat TapPay service and thankyou.html

### PR DESCRIPTION
**Pull request by jamieyu0914**
Hi @cwpeng ,

I'm 字涵.

In this commit, I tried to feat `TapPay service` and `thankyou.html`.

And, here is the required link below:

http://3.232.42.27:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. We should delete booking data after successful ordering.
2. Padding, border and size of inputs for credit cards should align with design, similar to contact inputs.

**Comment by jamieyu0914** [comment]
Hello @cwpeng ,

According to the issues, 
I tried to fix `the booking and ordering process`, as well as `the design of the credit card inputs` in latest version.

And, here is the required link below:

http://3.232.42.27:3000/

**Comment by cwpeng** [comment]
Should I review this?

**Comment by jamieyu0914** [comment]
> Should I review this?



> requested a review

Oh! Yeah. 🤣
I happened to be confirming the booking and ordering process in AWS before I asked for a re-review.

**Review by cwpeng — APPROVED** [review]
Good. :)

**Pull request merged**
