### PR TITLE
3st develop Commit 1129 -- Final Version for ubuntu in AWS -- tried to solve the padding problems

### PR DESCRIPTION
**Pull request by jamieyu0914**
Hi @cwpeng ,

I finished the progress of this week in this commit version.

Here is  the required link below:

[http://3.232.42.27:3000/](http://3.232.42.27:3000/)

Thanks a lot!

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your code will load the same page multiple times if we scroll down and up quickly. Try testing in live URL, not just in your local machine.
2. Layout issue: alignment, font-size, padding, image repeating.

**Comment by jamieyu0914** [comment]
Hello @cwpeng ,

In the latest commit, I added setTimeout() to prevent repeated loading actions. And, tried to fix the RWD issue.

Here is  the required link below:

[http://3.232.42.27:3000/](http://3.232.42.27:3000/)

**Comment by jamieyu0914** [comment]
Hello @cwpeng ,

In the latest commit, I added setTimeout() to prevent repeated loading actions. And, tried to fix the RWD issue.

Here is  the required link below:

[http://3.232.42.27:3000/](http://3.232.42.27:3000/)

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Your code never show attracions of final page.
2. Padding is not properly setup in many elements.
3. In mobile version, title is breaking to lines.

**Comment by jamieyu0914** [comment]
Hi @cwpeng ,

I tried to fix the final page, nextPage, undefined data, padding, and mobile version problems in the latest version.

Here is  the required link below:

[http://3.232.42.27:3000/](http://3.232.42.27:3000/)

**Comment by jamieyu0914** [comment]
Hi @cwpeng ,

I tried to fix the final page, nextPage, undefined data, padding, change welcome.png, and mobile version problems in the latest version.

Here is  the required link below:

[http://3.232.42.27:3000/](http://3.232.42.27:3000/)

**Review by cwpeng — CHANGES_REQUESTED** [review]
Padding is not properly setup in many elements.

**Comment by jamieyu0914** [comment]
Hello @cwpeng ,

In this version, I tried to solve the padding problems.

Here is  the required link below:

[http://3.232.42.27:3000/](http://3.232.42.27:3000/)

**Review by cwpeng — APPROVED** [review]
OK. Finally Done. Keep Forward. :)

**Pull request merged**
