### PR TITLE
1st develop Commit 1211 -- fix sign out problems

### PR DESCRIPTION
**Pull request by jamieyu0914**
Hi @cwpeng ,

I'm 字涵.

This week, I tried to feat the four api of /api/user and /api/user/auth.
Also, using JWT to authenticate the state of sign up or sign in.

Here is the required link below:

http://3.232.42.27:3000/
http://3.232.42.27:3000/attraction/220

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Password input should use input element with type password.

**Comment by jamieyu0914** [comment]
Hello @cwpeng ,

I fixed input element with type password in this commit version.

Here is the same required link below:

http://3.232.42.27:3000/
http://3.232.42.27:3000/attraction/220

**Review by cwpeng — CHANGES_REQUESTED** [review]
Sign out does not work properly. We should make sure API is completed before reloading page.

**Comment by jamieyu0914** [comment]
Hi @cwpeng ,

I'm trying to adjust the functions to wait for the sign out API return `data["ok"] == true` before reload the page.

Here is the same required link below:

http://3.232.42.27:3000/
http://3.232.42.27:3000/attraction/220

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
