### PR TITLE
1st develop Commit 1219 -- fix getData() and getbookingData()

### PR DESCRIPTION
**Pull request by jamieyu0914**
Hi @cwpeng ,

I'm 字涵.

In this commit, I finished the progress of this week.

And, here is the required link below:

http://3.232.42.27:3000/
http://3.232.42.27:3000/attraction/220
http://3.232.42.27:3000/booking

### CODE REVIEW

**Review by cwpeng — COMMENTED** [review]
Your APIs are broken.

**Comment by jamieyu0914** [comment]
Hello @cwpeng ,

I tried to fixed api problems and AJAX functions in latest commit version.

And, here is the same required link below:

http://3.232.42.27:3000/
http://3.232.42.27:3000/attraction/220
http://3.232.42.27:3000/booking

**Review by cwpeng — CHANGES_REQUESTED** [review]
Because we accpet only 1 attraction in booking, new booking attraction will replace old one. So, if we delete attration in booking page, it should change to empty, not previous one.

**Comment by jamieyu0914** [comment]
Hi @cwpeng ,

Due to solve this case, I tried to fix api issue of booking functions in this commit.

And, here is the same required link below:

http://3.232.42.27:3000/
http://3.232.42.27:3000/attraction/220
http://3.232.42.27:3000/booking

**Review by cwpeng — CHANGES_REQUESTED** [review]
In booking page, we should make sure that getBookingData() executes after completion of getUserData(), or your booking page cannot always work successfully.
未命名-2

**Comment by jamieyu0914** [comment]
Hi @cwpeng ,

I tried to adjust the position of getbookingData() to confirm the completion status of getData() .

And, here is the same required link below:

http://3.232.42.27:3000/
http://3.232.42.27:3000/attraction/220
http://3.232.42.27:3000/booking

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
