### PR TITLE
4st develop Commit 1119 -- Final Version for ubuntu in AWS

### PR DESCRIPTION
**Pull request by jamieyu0914**
Hi @cwpeng ,

I'm Jamie Yu. I done the part1-1 ~ part1-3, and this is the final version~

There are the required links below:

[http://3.232.42.27:3000/api/attraction?page=1](http://3.232.42.27:3000/api/attraction?page=1)
[http://3.232.42.27:3000/api/attractions?page=0&keyword=藝文館所](http://3.232.42.27:3000/api/attraction?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80)
[http://3.232.42.27:3000/api/attraction?page=0&keyword=北](http://3.232.42.27:3000/api/attraction?page=0&keyword=北) 
[http://3.232.42.27:3000/api/attraction/10](http://3.232.42.27:3000/api/attraction/10)

Have a nice day!

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Some issues below:

1. Response format of http://3.232.42.27:3000/api/attraction/10 is incorrect.
2. Use `LIMIT` to do range selection, not do it in your own code.

Solve them and re-request review.

**Comment by jamieyu0914** [comment]
Hello @cwpeng ,

okay~~

I already tried to adjust the Response format of [http://3.232.42.27:3000/api/attraction/10](http://3.232.42.27:3000/api/attraction/10). 
Also, Use `LIMIT` or `DISTINCT`  to do range selection by SQL.

There are the same required links below:

[http://3.232.42.27:3000/api/attraction?page=1](http://3.232.42.27:3000/api/attraction?page=1)
[http://3.232.42.27:3000/api/attractions?page=0&keyword=藝文館所](http://3.232.42.27:3000/api/attraction?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80)
[http://3.232.42.27:3000/api/attraction?page=0&keyword=北](http://3.232.42.27:3000/api/attraction?page=0&keyword=北) 
[http://3.232.42.27:3000/api/attraction/10](http://3.232.42.27:3000/api/attraction/10)

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by jamieyu0914 — COMMENTED** [review]
Hello @cwpeng ,

okay~~

I already tried to adjust the Response format of http://3.232.42.27:3000/api/attraction/10.
Also, Use `LIMIT` or `DISTINCT` to do range selection by SQL and fix `/api/attraction` in the latest commit version.

There are the same required links below:

http://3.232.42.27:3000/api/attraction?page=1
[http://3.232.42.27:3000/api/attractions?page=0&keyword=藝文館所](http://3.232.42.27:3000/api/attraction?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80)
[http://3.232.42.27:3000/api/attraction?page=0&keyword=北](http://3.232.42.27:3000/api/attraction?page=0&keyword=%E5%8C%97)
http://3.232.42.27:3000/api/attraction/10

**Review by cwpeng — APPROVED** [review]
Good. Done. :)

**Pull request merged**
